#!/bin/bash

exec < /dev/tty
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
make test
exit_status=$?
if [ "$exit_status" -ne 0 ]; then
  echo "Make test or check did not pass please resolve issues and try again."
  exit 1
fi
