version: "3"

services:
  ui:
    image: persona
    container_name: ui
    command: dev
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    #expose:
    #  - "5050"
    ports:
      - "5050:5050"
    volumes:
      - ./app:/app
