version: "3"

services:
  ui:
    image: ${BUILD_TARGET_ui:-base_ui}
    container_name: ${BUILD_TARGET_ui:-base_ui}
    command: dev
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-base}
    #expose:
    #  - "5050"
    ports:
      - "5050:5050"
    volumes:
      - ./app:/app
